[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_SANITY_PROJECT_ID = "6zuqzp5l"
  NEXT_PUBLIC_SANITY_DATASET = "staging"