[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.11.1"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_FORCE_EDGE_IMAGES = "true"

[dev]
  framework = "next"
  targetPort = 3003
  port = 8888
  autoLaunch = true
  command = "pnpm run dev"
  publish = ".next"
  functions = "netlify/functions"
  NODE_ENV = "development"
  watch = true
  debug = true

[functions]
  node_bundler = "esbuild"

# [functions]
#   node_bundler = "esbuild"
#   external_node_modules = ["axios", "form-data", "formidable", "node-fetch", "uuid", "parse-multipart-data"]
#   included_files = ["netlify/functions/**/*"]

# [functions."*"]
#   node_bundler = "esbuild"

# Specific rules first
[[redirects]]
  from = "/:lang/api/searchairportsbyterm"
  to = "/.netlify/functions/searchAirports"
  status = 200
  force = true

[[redirects]]
  from = "/:lang/api/searchflightsbyfromiatatoiatadatenumber"
  to = "/.netlify/functions/searchFlights"
  status = 200
  force = true # Assuming this might need force=true as well

[[redirects]]
  from = "/api/calculatecompensationbyfromiatatoiata"
  to = "/.netlify/functions/calculateCompensation"
  status = 200
  force = true

[[redirects]]
  from = "/:lang/api/evaluateeuflightclaim"
  to = "/.netlify/functions/evaluateeuflightclaim"
  status = 200
  force = true # Assuming this might need force=true as well

[[redirects]]
  from = "/:lang/api/ordereuflightclaim"
  to = "/.netlify/functions/ordereuflightclaim"
  status = 200
  force = true # Assuming this might need force=true as well

[[redirects]]
  from = "/:lang/api/submitflightnotlisted"
  to = "/.netlify/functions/submitFlightNotListed"
  status = 200
  force = true # Assuming this might need force=true as well

# General language-prefixed rules next
[[redirects]]
  from = "/:lang/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/:lang/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Fallback non-language-prefixed rule last
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"