[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/searchairportsbyterm"
  to = "/.netlify/functions/searchAirports"
  status = 200

[[redirects]]
  from = "/api/searchflightsbyfromiatatoiatadatenumber"
  to = "/.netlify/functions/searchFlights"
  status = 200

[[redirects]]
  from = "/api/calculatecompensationbyfromiatatoiata"
  to = "/.netlify/functions/calculateCompensation"
  status = 200

[[redirects]]
  from = "/api/evaluateeuflightclaim"
  to = "/.netlify/functions/evaluateeuflightclaim"
  status = 200

[[redirects]]
  from = "/api/ordereuflightclaim"
  to = "/.netlify/functions/orderEuFlightClaim"
  status = 200