[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_FORCE_EDGE_IMAGES = "true"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/searchairportsbyterm"
  to = "/.netlify/functions/searchAirports"
  status = 200

[[redirects]]
  from = "/api/searchflightsbyfromiatatoiatadatenumber"
  to = "/.netlify/functions/searchFlights"
  status = 200

[[redirects]]
  from = "/api/calculatecompensationbyfromiatatoiata"
  to = "/.netlify/functions/calculateCompensation"
  status = 200

[[redirects]]
  from = "/api/evaluateeuflightclaim"
  to = "/.netlify/functions/evaluateeuflightclaim"
  status = 200

[[redirects]]
  from = "/api/ordereuflightclaim"
  to = "/.netlify/functions/ordereuflightclaim"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"