import type { CountryOption } from '@/components/shared/CountryAutocomplete';

export const COUNTRY_OPTIONS: CountryOption[] = [
  { value: 'DEU', label: 'Deutschland' },
  { value: 'AUT', label: 'Österreich' },
  { value: 'CHE', label: 'Schweiz' },
  { value: 'FRA', label: 'Frankreich' },
  { value: 'ITA', label: 'Italien' },
  { value: 'ESP', label: 'Spanien' },
  { value: 'NLD', label: 'Niederlande' },
  { value: 'BEL', label: 'Belgien' },
  { value: 'DNK', label: 'Dänemark' },
  { value: 'POL', label: 'Polen' },
  { value: 'SWE', label: 'Schweden' },
  { value: 'NOR', label: 'Norwegen' },
  { value: 'FIN', label: 'Finnland' },
  { value: 'GRC', label: 'Griechenland' },
  { value: 'PRT', label: 'Portugal' },
  { value: 'IRL', label: 'Irland' },
  { value: 'GBR', label: 'Großbritannien' },
  { value: 'CZE', label: 'Tschechien' },
  { value: 'HUN', label: 'Ungarn' },
  { value: 'HRV', label: 'Kroatien' },
  { value: 'SVK', label: 'Slowakei' },
  { value: 'SVN', label: 'Slowenien' },
  { value: 'ROU', label: 'Rumänien' },
  { value: 'BGR', label: 'Bulgarien' },
  { value: 'USA', label: 'Vereinigte Staaten' },
  { value: 'CAN', label: 'Kanada' },
  { value: 'JPN', label: 'Japan' },
  { value: 'CHN', label: 'China' },
  { value: 'AUS', label: 'Australien' },
  { value: 'RUS', label: 'Russland' },
  { value: 'BRA', label: 'Brasilien' },
  { value: 'IND', label: 'Indien' },
  { value: 'MEX', label: 'Mexiko' },
  { value: 'ZAF', label: 'Südafrika' },
  { value: 'EGY', label: 'Ägypten' },
];
