import type { CountryOption } from '@/components/shared/CountryAutocomplete';

export const COUNTRY_OPTIONS: CountryOption[] = [
  { value: 'DEU', label: 'Deutschland', germanName: 'Deutschland' },
  { value: 'AUT', label: 'Österreich', germanName: 'Österreich' },
  { value: 'CHE', label: 'Schweiz', germanName: 'Schweiz' },
  { value: 'FRA', label: 'Frankreich', germanName: 'Frankreich' },
  { value: 'ITA', label: 'Italien', germanName: 'Italien' },
  { value: 'ESP', label: 'Spanien', germanName: 'Spanien' },
  { value: 'GBR', label: 'Großbritannien', germanName: 'Großbritannien' },
  { value: 'NLD', label: 'Niederlande', germanName: 'Niederlande' },
  { value: 'BEL', label: 'Belgien', germanName: 'Belgien' },
  { value: 'POL', label: 'Polen', germanName: 'Polen' },
  { value: 'CZE', label: 'Tschechien', germanName: 'Tschechien' },
  { value: 'GRC', label: 'Griechenland', germanName: 'Griechenland' },
  { value: 'PRT', label: 'Portugal', germanName: 'Portugal' },
  { value: 'SWE', label: 'Schweden', germanName: 'Schweden' },
  { value: 'HUN', label: 'Ungarn', germanName: 'Ungarn' },
  { value: 'DNK', label: 'Dänemark', germanName: 'Dänemark' },
  { value: 'FIN', label: 'Finnland', germanName: 'Finnland' },
  { value: 'SVK', label: 'Slowakei', germanName: 'Slowakei' },
  { value: 'NOR', label: 'Norwegen', germanName: 'Norwegen' },
  { value: 'IRL', label: 'Irland', germanName: 'Irland' },
  { value: 'HRV', label: 'Kroatien', germanName: 'Kroatien' },
  { value: 'SVN', label: 'Slowenien', germanName: 'Slowenien' },
  { value: 'LTU', label: 'Litauen', germanName: 'Litauen' },
  { value: 'LVA', label: 'Lettland', germanName: 'Lettland' },
  { value: 'EST', label: 'Estland', germanName: 'Estland' },
  { value: 'ROU', label: 'Rumänien', germanName: 'Rumänien' },
  { value: 'BGR', label: 'Bulgarien', germanName: 'Bulgarien' },
  { value: 'ISL', label: 'Island', germanName: 'Island' },
  { value: 'LUX', label: 'Luxemburg', germanName: 'Luxemburg' },
  { value: 'MLT', label: 'Malta', germanName: 'Malta' },
  { value: 'CYP', label: 'Zypern', germanName: 'Zypern' },
  {
    value: 'USA',
    label: 'Vereinigte Staaten',
    germanName: 'Vereinigte Staaten',
  },
  { value: 'CAN', label: 'Kanada', germanName: 'Kanada' },
  { value: 'AUS', label: 'Australien', germanName: 'Australien' },
  { value: 'JPN', label: 'Japan', germanName: 'Japan' },
  { value: 'CHN', label: 'China', germanName: 'China' },
  { value: 'IND', label: 'Indien', germanName: 'Indien' },
  { value: 'BRA', label: 'Brasilien', germanName: 'Brasilien' },
  { value: 'RUS', label: 'Russland', germanName: 'Russland' },
  { value: 'ZAF', label: 'Südafrika', germanName: 'Südafrika' },
  { value: 'EGY', label: 'Ägypten', germanName: 'Ägypten' },
];
