/**
 * Utility functions for airport data
 */

// Map of common airport codes to English city names
const AIRPORT_CITY_MAP_EN: Record<string, string> = {
  // Germany
  'BER': 'Berlin',
  'FRA': 'Frankfurt',
  'MUC': 'Munich',
  'HAM': 'Hamburg',
  'DUS': 'Düsseldorf',
  'STR': 'Stuttgart',
  'CGN': 'Cologne',
  'NUE': 'Nuremberg',
  'LEJ': 'Leipzig',
  'HAJ': 'Hannover',
  'DRS': 'Dresden',
  'FKB': 'Karlsruhe/Baden-Baden',
  'FDH': 'Friedrichshafen',
  'SCN': 'Saarbrücken',
  'PAD': 'Paderborn',
  'BRE': 'Bremen',
  'ERF': 'Erfurt',
  'FMO': 'Münster',
  'HHN': 'Frankfurt-Hahn',
  'FMM': 'Memmingen',

  // Europe
  'LHR': 'London',
  'LGW': 'London Gatwick',
  'STN': 'London Stansted',
  'LTN': 'London Luton',
  'LCY': 'London City',
  'CDG': 'Paris',
  'ORY': 'Paris Orly',
  'BVA': 'Paris Beauvais',
  'FCO': 'Rome',
  'CIA': 'Rome Ciampino',
  'MAD': 'Madrid',
  'BCN': 'Barcelona',
  'AMS': 'Amsterdam',
  'VIE': 'Vienna',
  'ZRH': 'Zurich',
  'GVA': 'Geneva',
  'BRU': 'Brussels',
  'CRL': 'Brussels Charleroi',
  'ATH': 'Athens',
  'LIS': 'Lisbon',
  'OPO': 'Porto',
  'OSL': 'Oslo',
  'ARN': 'Stockholm',
  'CPH': 'Copenhagen',
  'HEL': 'Helsinki',
  'PRG': 'Prague',
  'BUD': 'Budapest',
  'WAW': 'Warsaw',
  'KRK': 'Krakow',
  'DME': 'Moscow',
  'SVO': 'Moscow Sheremetyevo',
  'LED': 'St. Petersburg',
  'IST': 'Istanbul',
  'SAW': 'Istanbul Sabiha',
  'DUB': 'Dublin',
  'MAN': 'Manchester',
  'EDI': 'Edinburgh',
  'GLA': 'Glasgow',
  'BFS': 'Belfast',
  'MXP': 'Milan',
  'LIN': 'Milan Linate',
  'BGY': 'Milan Bergamo',
  'VCE': 'Venice',
  'NAP': 'Naples',
  'PMO': 'Palermo',
  'CTA': 'Catania',
  'AGP': 'Malaga',
  'ALC': 'Alicante',
  'PMI': 'Palma de Mallorca',
  'IBZ': 'Ibiza',
  'TFS': 'Tenerife',
  'LPA': 'Gran Canaria',
  'ACE': 'Lanzarote',
  'FAO': 'Faro',
  'OTP': 'Bucharest',
  'SOF': 'Sofia',
  'SKG': 'Thessaloniki',
  'RIX': 'Riga',
  'TLL': 'Tallinn',
  'VNO': 'Vilnius',
  'LJU': 'Ljubljana',
  'ZAG': 'Zagreb',
  'BEG': 'Belgrade',
  'TIV': 'Tivat',
  'KIV': 'Chisinau',
  'TGD': 'Podgorica',
  'SJJ': 'Sarajevo',
  'SKP': 'Skopje',
  'TIA': 'Tirana',
  'LCA': 'Larnaca',
  'PFO': 'Paphos',
  'MLA': 'Malta',
  'KEF': 'Reykjavik',

  // North America
  'JFK': 'New York',
  'LGA': 'New York LaGuardia',
  'EWR': 'New York Newark',
  'BOS': 'Boston',
  'IAD': 'Washington D.C.',
  'DCA': 'Washington D.C. National',
  'BWI': 'Baltimore',
  'PHL': 'Philadelphia',
  'ATL': 'Atlanta',
  'MIA': 'Miami',
  'FLL': 'Fort Lauderdale',
  'MCO': 'Orlando',
  'TPA': 'Tampa',
  'IAH': 'Houston',
  'HOU': 'Houston Hobby',
  'DFW': 'Dallas',
  'DAL': 'Dallas Love Field',
  'ORD': 'Chicago',
  'MDW': 'Chicago Midway',
  'DTW': 'Detroit',
  'MSP': 'Minneapolis',
  'CLT': 'Charlotte',
  'DEN': 'Denver',
  'PHX': 'Phoenix',
  'LAS': 'Las Vegas',
  'LAX': 'Los Angeles',
  'SNA': 'Orange County',
  'BUR': 'Burbank',
  'ONT': 'Ontario',
  'SAN': 'San Diego',
  'SFO': 'San Francisco',
  'OAK': 'Oakland',
  'SJC': 'San Jose',
  'PDX': 'Portland',
  'SEA': 'Seattle',
  'SLC': 'Salt Lake City',
  'YYZ': 'Toronto',
  'YUL': 'Montreal',
  'YVR': 'Vancouver',
  'YYC': 'Calgary',
  'YEG': 'Edmonton',
  'YOW': 'Ottawa',
  'YHZ': 'Halifax',
  'YWG': 'Winnipeg',
  'MEX': 'Mexico City',
  'CUN': 'Cancun',
  'GDL': 'Guadalajara',
  'MTY': 'Monterrey',

  // Asia
  'PEK': 'Beijing',
  'PKX': 'Beijing Daxing',
  'PVG': 'Shanghai',
  'SHA': 'Shanghai Hongqiao',
  'CAN': 'Guangzhou',
  'SZX': 'Shenzhen',
  'CTU': 'Chengdu',
  'HKG': 'Hong Kong',
  'TPE': 'Taipei',
  'NRT': 'Tokyo',
  'HND': 'Tokyo Haneda',
  'KIX': 'Osaka',
  'ITM': 'Osaka Itami',
  'FUK': 'Fukuoka',
  'CTS': 'Sapporo',
  'ICN': 'Seoul',
  'GMP': 'Seoul Gimpo',
  'SIN': 'Singapore',
  'KUL': 'Kuala Lumpur',
  'BKK': 'Bangkok',
  'DMK': 'Bangkok Don Mueang',
  'SGN': 'Ho Chi Minh City',
  'HAN': 'Hanoi',
  'MNL': 'Manila',
  'CGK': 'Jakarta',
  'DPS': 'Bali',
  'DEL': 'Delhi',
  'BOM': 'Mumbai',
  'MAA': 'Chennai',
  'BLR': 'Bangalore',
  'HYD': 'Hyderabad',
  'CCU': 'Kolkata',
  'CMB': 'Colombo',
  'KTM': 'Kathmandu',
  'DXB': 'Dubai',
  'AUH': 'Abu Dhabi',
  'DOH': 'Doha',
  'BAH': 'Bahrain',
  'MCT': 'Muscat',
  'RUH': 'Riyadh',
  'JED': 'Jeddah',
  'AMM': 'Amman',
  'BEY': 'Beirut',
  'TLV': 'Tel Aviv',

  // Australia & Oceania
  'SYD': 'Sydney',
  'MEL': 'Melbourne',
  'BNE': 'Brisbane',
  'PER': 'Perth',
  'ADL': 'Adelaide',
  'CBR': 'Canberra',
  'HBA': 'Hobart',
  'DRW': 'Darwin',
  'AKL': 'Auckland',
  'CHC': 'Christchurch',
  'WLG': 'Wellington',
  'ZQN': 'Queenstown',
  'NAN': 'Nadi',
  'PPT': 'Tahiti',
  'APW': 'Apia',
  'TBU': 'Tonga',
  'HIR': 'Honiara',
  'VLI': 'Port Vila',
  'NOU': 'Noumea',
  'GUM': 'Guam',

  // Africa
  'CAI': 'Cairo',
  'CPT': 'Cape Town',
  'JNB': 'Johannesburg',
  'DUR': 'Durban',
  'LOS': 'Lagos',
  'ACC': 'Accra',
  'NBO': 'Nairobi',
  'DAR': 'Dar es Salaam',
  'ADD': 'Addis Ababa',
  'CMN': 'Casablanca',
  'ALG': 'Algiers',
  'TUN': 'Tunis',
  'MIR': 'Monastir',
  'DJE': 'Djerba',
  'HRG': 'Hurghada',
  'SSH': 'Sharm El Sheikh',
  'LXR': 'Luxor',
  'RAK': 'Marrakech',
  'DSS': 'Dakar',
  'ABJ': 'Abidjan',
  'LFW': 'Lome',
  'COO': 'Cotonou',
  'OUA': 'Ouagadougou',
  'BKO': 'Bamako',
  'NKC': 'Nouakchott',
  'CKY': 'Conakry',
  'FIH': 'Kinshasa',
  'FBM': 'Lubumbashi',
  'KGL': 'Kigali',
  'BJM': 'Bujumbura',
  'EBB': 'Entebbe',
  'JRO': 'Kilimanjaro',
  'ZNZ': 'Zanzibar',
  'MRU': 'Mauritius',
  'SEZ': 'Seychelles',
  'TNR': 'Antananarivo',
  'DZA': 'Dzaoudzi',
  'RUN': 'Reunion',
  'WDH': 'Windhoek',
  'GBE': 'Gaborone',
  'HRE': 'Harare',
  'LUN': 'Lusaka',
  'BLZ': 'Blantyre',
  'LLW': 'Lilongwe',

  // South America
  'GRU': 'São Paulo',
  'CGH': 'São Paulo Congonhas',
  'GIG': 'Rio de Janeiro',
  'SDU': 'Rio de Janeiro Santos Dumont',
  'BSB': 'Brasília',
  'CNF': 'Belo Horizonte',
  'SSA': 'Salvador',
  'REC': 'Recife',
  'FOR': 'Fortaleza',
  'CWB': 'Curitiba',
  'POA': 'Porto Alegre',
  'FLN': 'Florianópolis',
  'EZE': 'Buenos Aires',
  'AEP': 'Buenos Aires Jorge Newbery',
  'COR': 'Córdoba',
  'MDZ': 'Mendoza',
  'SCL': 'Santiago',
  'LIM': 'Lima',
  'CUZ': 'Cusco',
  'BOG': 'Bogotá',
  'MDE': 'Medellín',
  'CTG': 'Cartagena',
  'CLO': 'Cali',
  'UIO': 'Quito',
  'GYE': 'Guayaquil',
  'CCS': 'Caracas',
  'MVD': 'Montevideo',
  'ASU': 'Asunción',
  'VVI': 'Santa Cruz',
  'LPB': 'La Paz',
  'GEO': 'Georgetown',
  'PBM': 'Paramaribo',
  'CAY': 'Cayenne'
};

// Map of common airport codes to German city names
const AIRPORT_CITY_MAP_DE: Record<string, string> = {
  // Germany
  'BER': 'Berlin',
  'FRA': 'Frankfurt',
  'MUC': 'München',
  'HAM': 'Hamburg',
  'DUS': 'Düsseldorf',
  'STR': 'Stuttgart',
  'CGN': 'Köln',
  'NUE': 'Nürnberg',
  'LEJ': 'Leipzig',
  'HAJ': 'Hannover',
  'DRS': 'Dresden',
  'FKB': 'Karlsruhe/Baden-Baden',
  'FDH': 'Friedrichshafen',
  'SCN': 'Saarbrücken',
  'PAD': 'Paderborn',
  'BRE': 'Bremen',
  'ERF': 'Erfurt',
  'FMO': 'Münster',
  'HHN': 'Frankfurt-Hahn',
  'FMM': 'Memmingen',

  // Europe
  'LHR': 'London',
  'LGW': 'London Gatwick',
  'STN': 'London Stansted',
  'LTN': 'London Luton',
  'LCY': 'London City',
  'CDG': 'Paris',
  'ORY': 'Paris Orly',
  'BVA': 'Paris Beauvais',
  'FCO': 'Rom',
  'CIA': 'Rom Ciampino',
  'MAD': 'Madrid',
  'BCN': 'Barcelona',
  'AMS': 'Amsterdam',
  'VIE': 'Wien',
  'ZRH': 'Zürich',
  'GVA': 'Genf',
  'BRU': 'Brüssel',
  'CRL': 'Brüssel Charleroi',
  'ATH': 'Athen',
  'LIS': 'Lissabon',
  'OPO': 'Porto',
  'OSL': 'Oslo',
  'ARN': 'Stockholm',
  'CPH': 'Kopenhagen',
  'HEL': 'Helsinki',
  'PRG': 'Prag',
  'BUD': 'Budapest',
  'WAW': 'Warschau',
  'KRK': 'Krakau',
  'DME': 'Moskau',
  'SVO': 'Moskau Scheremetjewo',
  'LED': 'St. Petersburg',
  'IST': 'Istanbul',
  'SAW': 'Istanbul Sabiha',
  'DUB': 'Dublin',
  'MAN': 'Manchester',
  'EDI': 'Edinburgh',
  'GLA': 'Glasgow',
  'BFS': 'Belfast',
  'MXP': 'Mailand',
  'LIN': 'Mailand Linate',
  'BGY': 'Mailand Bergamo',
  'VCE': 'Venedig',
  'NAP': 'Neapel',
  'PMO': 'Palermo',
  'CTA': 'Catania',
  'AGP': 'Malaga',
  'ALC': 'Alicante',
  'PMI': 'Palma de Mallorca',
  'IBZ': 'Ibiza',
  'TFS': 'Teneriffa',
  'LPA': 'Gran Canaria',
  'ACE': 'Lanzarote',
  'FAO': 'Faro',
  'OTP': 'Bukarest',
  'SOF': 'Sofia',
  'SKG': 'Thessaloniki',
  'RIX': 'Riga',
  'TLL': 'Tallinn',
  'VNO': 'Vilnius',
  'LJU': 'Ljubljana',
  'ZAG': 'Zagreb',
  'BEG': 'Belgrad',
  'TIV': 'Tivat',
  'KIV': 'Chisinau',
  'TGD': 'Podgorica',
  'SJJ': 'Sarajevo',
  'SKP': 'Skopje',
  'TIA': 'Tirana',
  'LCA': 'Larnaka',
  'PFO': 'Paphos',
  'MLA': 'Malta',
  'KEF': 'Reykjavik',

  // Major international cities
  'JFK': 'New York',
  'LAX': 'Los Angeles',
  'ORD': 'Chicago',
  'DFW': 'Dallas',
  'HKG': 'Hongkong',
  'NRT': 'Tokio',
  'SIN': 'Singapur',
  'DXB': 'Dubai',
  'SYD': 'Sydney',
  'YYZ': 'Toronto',
  'YUL': 'Montreal',
  'YVR': 'Vancouver',
  'PEK': 'Peking',
  'PVG': 'Shanghai',
  'DEL': 'Delhi',
  'BOM': 'Mumbai',
  'GRU': 'São Paulo',
  'EZE': 'Buenos Aires',
  'CPT': 'Kapstadt',
  'JNB': 'Johannesburg',
  'CAI': 'Kairo'
};

/**
 * Get the city name for an airport code
 * @param code The IATA airport code (e.g., "BER")
 * @param lang The language code (e.g., "en" or "de")
 * @returns The city name (e.g., "Berlin") or the original code if not found
 */
export const getAirportCity = (code: string | null | undefined, lang: string = 'en'): string => {
  if (!code) return '';

  const upperCode = code.toUpperCase();

  // Use the appropriate language map
  if (lang === 'de') {
    return AIRPORT_CITY_MAP_DE[upperCode] || upperCode;
  }

  // Default to English
  return AIRPORT_CITY_MAP_EN[upperCode] || upperCode;
};

/**
 * Get the city name from a location object or string
 * @param location A location object or string
 * @param lang The language code (e.g., "en" or "de")
 * @returns The city name or the original location value if not found
 */
export const getLocationCity = (location: any, lang: string = 'en'): string => {
  if (!location) return '';

  // If it's a location object with a city property, use that
  if (typeof location === 'object' && location !== null) {
    if (location.city) return location.city;

    // Try to get the value property if it exists
    const code = location.value || location.label || '';
    return getAirportCity(code, lang);
  }

  // If it's a string (airport code), try to get the city name
  if (typeof location === 'string') {
    return getAirportCity(location, lang);
  }

  return '';
};